### ISSUE TITLE
Cannot specify port to connect to

### ISSUE THREAD

**Issue by ajvpot** [mmcgill/mc3p#1]
I can't seem to specify a port to connect to.

<pre>$ python -m mc3p.proxy -p 25565 108.60.193.139 25965
ERROR:mc3p:Couldn't connect to 108.60.193.139:25565 - [Errno 110] Connection timed out

$ python -m mc3p.proxy -p 25565 108.60.193.139:25965
ERROR:mc3p:Couldn't connect to 108.60.193.139:25965:25565 - [Errno -2] Name or service not known
</pre>

**Comment by mmcgill** [comment]
*facepalm* Thanks. Fix is checked in.
